DatasetAttribution:
    - "© xcube & eo4natura"

DatasetChunkCacheSize: 250M

## You may want to specify a location of your server resources.
#base_dir: s3://<bucket>/<path-to-your>/<resources>/

## You may want to specify a remote location of your viewer resources.
# Viewer:
#     Configuration:
#         Path: https://eo4naturabucketpublic.s3.us-west-2.amazonaws.com/config.json

DataStores:
    # # This section needs to be kept, because it is part of xcube server documentation using DataStores.
    - Identifier: eo4natura
      StoreId: s3
      StoreParams:
          root: eo4naturazarr2/ndvi_from_aurora_with_pyramids.zarr
          max_depth: 1
          storage_options:
              anon: false
              key: ${AWS_ACCESS_KEY_ID}
              secret: ${AWS_SECRET_ACCESS_KEY}
      Datasets:
          - Identifier: eo4natura_s3_1
            Title: Datacube 01 3Is Stretched March 2023
            GroupTitle: Zarr
            # BoundingBox: [0.0, 50, 5.0, 52.5]
            Path: "cube_3Is_streched_2023-03-01_2023-03-30.zarr"
            Style: S2L2A
            ChunkCacheSize: 250M
            # PlaceGroups:
            #     - PlaceGroupRef: inside-cube
            #     - PlaceGroupRef: outside-cube
            # AccessControl:
            #     IsSubstitute: True
          - Identifier: eo4natura_s3_2
            Title: Datacube 02 3Is Stretched October 2023
            GroupTitle: Zarr
            # BoundingBox: [0.0, 50, 5.0, 52.5]
            Path: "cube_3Is_streched_2023-10-01_2023-10-30.zarr"
            Style: S2L2A
            ChunkCacheSize: 250M
            # PlaceGroups:
            #     - PlaceGroupRef: inside-cube
            #     - PlaceGroupRef: outside-cube
            # AccessControl:
            #     IsSubstitute: True

Styles:
    - Identifier: S2L2A
      ColorMappings:
          B01:
              ColorBar: "gray"
              ValueRange: [0., 0.25]
          B02_md:
              ColorBar: "gray"
              ValueRange: [0., 0.25]
          B03_md:
              ColorBar: "gray"
              ValueRange: [0., 0.25]
          B04_md:
              ColorBar: "gray"
              ValueRange: [0., 0.25]
          B05:
              ColorBar: "gray"
              ValueRange: [0., 0.25]
          B06:
              ColorBar: "gray"
              ValueRange: [0., 0.25]
          B07:
              ColorBar: "gray"
              ValueRange: [0., 0.25]
          B08:
              ColorBar: "gray"
              ValueRange: [0., 0.25]
          B8A:
              ColorBar: "gray"
              ValueRange: [0., 0.25]
          B09:
              ColorBar: "gray"
              ValueRange: [0., 0.25]
          B10:
              ColorBar: "gray"
              ValueRange: [0., 0.25]
          B11:
              ColorBar: "gray"
              ValueRange: [0., 0.25]
          B12:
              ColorBar: "gray"
              ValueRange: [0., 0.25]
          SCL:
              ColorBar: "gray"
              ValueRange: [0, 255]
          rgb:
              Red:
                  Variable: B04
                  ValueRange: [0., 0.25]
              Green:
                  Variable: B06
                  ValueRange: [0., 0.25]
              Blue:
                  Variable: B08
                  ValueRange: [0., 0.25]
          ndvi:
              ColorBar: "delta"
              ValueRange: [-1., 1.]

ServiceProvider:
    ProviderName: "Brockmann Consult GmbH"
    ProviderSite: "https://www.brockmann-consult.de"
    ServiceContact:
        IndividualName: "Norman Fomferra"
        PositionName: "Senior Software Engineer"
        ContactInfo:
            Phone:
                Voice: "+49 4152 889 303"
                Facsimile: "+49 4152 889 330"
            Address:
                DeliveryPoint: "HZG / GITZ"
                City: "Geesthacht"
                AdministrativeArea: "Herzogtum Lauenburg"
                PostalCode: "21502"
                Country: "Germany"
                ElectronicMailAddress: "norman.fomferra@brockmann-consult.de"
